### ISSUE TITLE
AFC-2343_HideMenues in DAFA

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#596]
**Userstory:** 
As a DAFA Accounting Read-user, I only want to see the relevant options in DAFA

1
![image](https://user-images.githubusercontent.com/61729317/119155084-17d7c280-ba53-11eb-9644-3983db7a717e.png)

![image](https://user-images.githubusercontent.com/61729317/119155232-3f2e8f80-ba53-11eb-9765-25cd17d1fa7b.png)

![image](https://user-images.githubusercontent.com/61729317/119166624-24faae80-ba5f-11eb-92a6-107a4f5af118.png)

![image](https://user-images.githubusercontent.com/61729317/119166803-596e6a80-ba5f-11eb-960f-bdd2a0cf8227.png)

2

![image](https://user-images.githubusercontent.com/61729317/119166703-3f348c80-ba5f-11eb-8d46-774e9b16c72e.png)

3
Add inheritance for user-group: 
Odoo standard user-group: "sales_team.group_sale_salesman_all_leads"
to 
"DAFA Accountant Read" in https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/base_user_groups_dafa

4
Change User-groups on the following meny-items: 

4a
Change in the normal place: 
odoo-outplacement/outplacement
"outplacement.outplacement_configuration","outplacement.group_outplacement_admin"

4b
These are special adjustments: 
"id","groups_id/id"
"sale.sale_menu_root","base_user_groups_dafa.group_dafa_admin_accounting_read"
"sale.menu_sale_order","base_user_groups_dafa.group_dafa_admin_accounting_read"
"sale.menu_sale_invoicing","base_user_groups_dafa.group_dafa_admin_accounting_read"
"sale.menu_sale_report","base_user_groups_dafa.group_dafa_admin_accounting_read"
"sale.menu_report_product_all","base_user_groups_dafa.group_dafa_admin_accounting_read"
"account.menu_account_customer","base.group_system","base_user_groups_dafa.group_dafa_admin_accounting_read"
"account.menu_finance","base_user_groups_dafa.group_dafa_admin_accounting_read"
"account.menu_action_account_payments_receivable","base.group_system"
"account.menu_action_invoice_tree1","base_user_groups_dafa.group_dafa_admin_accounting_read"
"account.menu_action_invoice_out_refund","base.group_system"
"account.menu_finance_configuration","base.group_system"
"account.menu_finance_payables","base.group_system"
"account.menu_finance_receivables","base.group_system","base_user_groups_dafa.group_dafa_admin_accounting_read"
"account.product_product_menu_sellable","base.group_system"

5
Add this to System Parameter (this prevents a module to over-right the module at upgrade)
id,"key","value"
__import__.ir_config_parameter_menu_noupdate,"ir.ui.menu","noupdate"

**Module name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/sale_outplacement

**Development Branch name:** 
Dev-12.0-AFC-2343-Hide-FinanceButtons-and-menues

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install the module...
Login with a user that has the user-rights "DAFA Accounting Read"
The buttons should not be visible.

**Description to the manifest:** 
AFC-2343 adds usergroups to buttons that hides them from the normal user.

**Comment by AnilKesariya** [comment]
@FredrikArvas : I've few question regarding DAFA and CRM thing and respective repositories to be used. let's discuss in daily standup meeting that is scheduled after 30 minute.

**Comment by AnilKesariya** [comment]
Hi Fredrik,

I've created https://github.com/vertelab/odoo-outplacement/pull/219 for the following.

CUD (create, update, delete)
1. Disable smart button on sales views and Disabled CUD  operations on form view of sale screen
2. Disable smart buttons on invoice views and Disabled CUD operations on form view invoice screen.

Here is the screenshot when user logged in with **DAFA Accounting (Read)** Group Access.

![dafa_read_inv_access](https://user-images.githubusercontent.com/5101994/119341349-47840600-bcb1-11eb-84d7-b5d02bde18c3.png)
![dafa_read_sale_access](https://user-images.githubusercontent.com/5101994/119341359-48b53300-bcb1-11eb-9611-b76bdf69a027.png)

Here is the video [link](https://www.loom.com/share/29dd7524e0ac4be08657c4148c053a00) recorded on loom.


About translation part need to connect with you to understand point 3,4 and 5

**Comment by AnilKesariya** [comment]
@FredrikArvas : let me know the right time to understand some pending points on this issue, which are not clear to me.

**Comment by AnilKesariya** [comment]
@FredrikArvas : Point 5 is not required to do as I've not applied the groups on menu to hide it. used dynamic fields_view_get which will hide the buttons and access right on view load.

**Comment by AnilKesariya** [comment]
![translation_terms](https://user-images.githubusercontent.com/5101994/119355036-63dc6e80-bcc2-11eb-8a73-91713f9bf7c9.png)

**Comment by AnilKesariya** [comment]
Hi Fredrik,

I've completed this task, here is the [PR](https://github.com/vertelab/odoo-outplacement/pull/219)

Here is the video for this task :
https://www.loom.com/share/97e1dd96ce48491f95f16b7dd814bd69

Code is already pushed, we can see on daily stand up

Regards,
Anil

**Comment by fredrikarvas-vertel** [comment]
Thanks @AnilKesariya.
Did you see that it did not work on my dev-server yesterday?

**Comment by AnilKesariya** [comment]
@FredrikArvas : yes radhika showed me yesterday, with this latest fix should work.

**Comment by fredrikarvas-vertel** [comment]
Great!
 I will test it now

**Comment by fredrikarvas-vertel** [comment]
Logged in with Accounting Read
![image](https://user-images.githubusercontent.com/61729317/119773170-84721780-bec0-11eb-87d1-5fd6b949f6ce.png)
![image](https://user-images.githubusercontent.com/61729317/119773215-96ec5100-bec0-11eb-9f2f-2d3ccb34ddb4.png)
![image](https://user-images.githubusercontent.com/61729317/119773243-9f448c00-bec0-11eb-9340-e833b54ee607.png)

**Comment by AnilKesariya** [comment]
@FredrikArvas : I've reproduced problem if credit and edit button after installing module.

Here is the video: https://www.loom.com/share/95200a2f855e41b09be5234032585e5e

Only the new button which are added from some custom module need to find out from where those are added those are not odoo standard buttons. the rest functionality of hiding menus and inside form view button is works perfectly fine with all modules.

I will check the not working part which is re-produced now.

Regards,
AK

**Comment by fredrikarvas-vertel** [comment]
Great!

**Comment by AnilKesariya** [comment]
There is one web module conflicts with this feature that does not allow to disable create and edit option. : web_a11y_create-buttons (odoo-web)

If I uninstall this then it works perfectly fine. so I am trying to figure out how I can resolve this problem a long with this app.

**Comment by fredrikarvas-vertel** [comment]
Ok. Great that you found the issue.
That module is important. 
So we need to think of a way to merge them somehow.

**Comment by AnilKesariya** [comment]
Yes, I see, it updates the buttons label. but it stopped allowing to update form attributes at all even though we can't update any attribute of form directly with this module.

**Comment by AnilKesariya** [comment]
@FredrikArvas, @Radhika435 

Please have a look at this video https://www.loom.com/share/8ac6fcbc941e4b5291cb114d42521159

Due that odoo-web custom module it shows create and edit button for any model even if users does not have the standard access of create,read. 

For now, I've added read access right for accounting read user for sale and accounting operations, even though create/edit button would be there but user will not able to perform any update or creation operation on sales and invoice with dafa read access.

I've pushed the changes to same dev branch : Dev-12.0-AFC-2343-Hide-FinanceButtons-and-menues
Code is in same PR : https://github.com/vertelab/odoo-outplacement/pull/219

Regards,
AK

**Comment by fredrikarvas-vertel** [comment]
ok, that is a good solution at this point.
Thanks

**Comment by fredrikarvas-vertel** [comment]
This item is still not working correctly, it might be due to a conflict with something else. I will ask @robch2342 have a look.

**Comment by AnilKesariya** [comment]
@FredrikArvas : after installing all dafa module got some problem with server_auth module.

https://www.loom.com/share/daba7bd3ffac47f08d0a385630ad50c0

Traceback (most recent call last):
  File "/home/server/workspace_ht/fredrik/DAFA/server-auth/auth_saml_ol/controllers/main.py", line 134, in get_auth_request
    auth_request, request_id = provider._get_auth_request(state)
  File "/home/server/workspace_ht/fredrik/DAFA/server-auth/auth_saml_ol/models/auth_saml.py", line 150, in _get_auth_request
    server = self._get_onelogin_server()
AttributeError: 'auth.saml.provider' object has no attribute '_get_onelogin_server'

I'm trying to check what is problem with this. Do you face the same issue?

Regards,

**Comment by AnilKesariya** [comment]
@FredrikArvas : is there is special lib for this? ModuleNotFoundError: No module named 'onelogin.saml2'
Standard installation for this library does not work.

Regards,

**Comment by AnilKesariya** [comment]
@FredrikArvas : I managed to install all the app, it works perfectly fine with all installed module. here is the video shared.

https://www.loom.com/share/c6cf5f549e8348f991d8deb1249f324d

Please do let me know if you need more info about this.

Regards,
Anil
